#!/bin/sh
#
# Pre-commit hook to run lint check before committing changes.

# Check that the code conforms to the style guide
if ! npm run lint --silent; then
  echo "Lint check failed. Please fix linting errors and try again."
  exit 1
fi

# If check passed, exit successfully
exit 0
