version: '3.9'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - JAVA_OPTS=-Xms1g -Xmx1g
    healthcheck:
      test: ['CMD-SHELL', 'curl --silent --fail localhost:9200/_cluster/health || exit 1']
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - '9200:9200'
    volumes:
      - ./data/terms/radlexterm.txt:/usr/share/elasticsearch/config/terms/radlexterm.txt:ro
      - ./data/elasticsearch:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    platform: linux/amd64
    restart: unless-stopped
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - XPACK_MONITORING_ENABLED=false
    healthcheck:
      test: ['CMD-SHELL', 'curl --silent --fail localhost:5601/api/status || exit 1']
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - '5601:5601'

  redis:
    image: redis
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/data

  mongo:
    image: mongo
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', 'db.adminCommand("ping")']
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      - MONGO_INITDB_DATABASE=micala
    ports:
      - '27017:27017'
    volumes:
      - ./data/mongo:/data/db

  micala:
    build: .
    restart: unless-stopped
    depends_on:
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_healthy
      mongo:
        condition: service_healthy
    env_file: .env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/micala
      - DATA_PATH=/data
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - '3000:3000'
    volumes:
      - ./data/micala:/data
