openapi: 3.0.3

info:
  title: Micala
  description: 醫療影像與報告查詢系統
  version: 1.0.0

servers:
  - url: 'http://localhost:3000'

paths:
  /reports/upload:
    post:
      summary: Upload reports
      description: Upload DICOM reports to the database.
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                patientId:
                  type: string
                reportNumber:
                  type: string
                files:
                  type: array
                  items:
                    type: string
                    description: .txt files
                    format: binary
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    enum: [true]
  /studies:
    get:
      summary: Get studies
      description: This endpoint allows you to get studies based on the provided query parameters.
      parameters:
        - in: query
          name: modality
          schema:
            type: string
          description: The modality of the study.
          required: false
        - in: query
          name: patientId
          schema:
            type: number
          description: The patient ID of the study.
          required: false
        - in: query
          name: patientName
          schema:
            type: string
          description: The patient name of the study.
          required: false
        - in: query
          name: fromDate
          schema:
            type: string
            format: date
          description: Select studies from this date onwards.
          required: false
        - in: query
          name: toDate
          schema:
            type: string
            format: date
          description: Select studies up to this date.
          required: false
        - in: query
          name: identifier
          schema:
            type: string
          description: The study instance UID.
          required: false
      responses:
        '200':
          description: A list of studies.
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    enum: [true]
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Study'
  /studies/:studyUid/series:
    get:
      summary: Get series
      description: This endpoint allows you to get series of the specified study.
      parameters:
        - in: path
          name: studyUid
          schema:
            type: string
          description: The UID of the study.
          required: true
      responses:
        '200':
          description: A list of series.
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    enum: [true]
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Series'
  /studies/:studyUid/series/:seriesUid/instances:
    get:
      summary: Get instances
      description: This endpoint allows you to get instances of the specified series.
      parameters:
        - in: path
          name: studyUid
          schema:
            type: string
          description: The UID of the study.
          required: true
        - in: path
          name: seriesUid
          schema:
            type: string
          description: The UID of the series.
          required: true
      responses:
        '200':
          description: A list of instances.
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    enum: [true]
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Instance'
  /studies/index:
    post:
      summary: Index a study
      description: Index a DICOM study specified by its UID in the search engine.
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /studies/search:
    get:
      summary: Search studies
      description: Search studies in the search engine.
      parameters:
        - name: search
          description: The search query.
          in: query
          required: true
          schema:
            type: string
        - name: instance
          description: The UID of the instance.
          in: query
          schema:
            type: string
        - name: modality
          in: query
          schema:
            type: string
        - name: patientId
          in: query
          schema:
            type: string
        - name: patientName
          in: query
          schema:
            type: string
        - name: fromDate
          in: query
          schema:
            type: string
            format: date
        - name: toDate
          in: query
          schema:
            type: string
            format: date
        - name: gender
          in: query
          schema:
            type: array
            items:
              type: string
        - name: category
          in: query
          schema:
            type: array
            items:
              type: string
        - name: limit
          in: query
          schema:
            type: integer
        - name: offset
          in: query
          schema:
            type: integer
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    enum: [true]
                  facets:
                    type: object
                    properties:
                      gender:
                        $ref: '#/components/schemas/FacetOptions'
                      category:
                        $ref: '#/components/schemas/FacetOptions'
                  studies:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        thumbnail:
                          type: string
                          format: url
                        report:
                          type: string
                  total:
                    type: integer
  /studies/upload:
    post:
      summary: Upload a study
      description: Upload DICOM files and index them in the search engine. Note that this request may take a while to complete.
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: array
                  items:
                    type: string
                    format: binary
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    enum: [true]
                  studyUids:
                    type: array
                    items:
                      type: string
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /terms/suggestions:
    get:
      summary: Get term suggestions
      description: Get term suggestions for the search query.
      parameters:
        - name: search
          description: The search query.
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    key:
                      type: string
                    doc_count:
                      type: integer
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /thumbnails/{filename}:
    get:
      summary: Get a thumbnail
      description: Get a thumbnail by its filename.
      parameters:
        - name: filename
          description: The filename of the thumbnail.
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            image/jpeg:
              schema:
                type: string
                format: binary
        404:
          description: Not Found

components:
  schemas:
    Study:
      type: object
      properties:
        studyDate:
          type: string
          description: The date of the study.
        description:
          type: string
          description: The description of the study.
        patientName:
          type: string
          description: The name of the patient.
        patientId:
          type: string
          description: The ID of the patient.
        studyUid:
          type: string
          description: The UID of the study.
        retrieveUrl:
          type: string
          description: The URL to retrieve the study.
        seriesUrl:
          type: string
          description: The URL to retrieve the series of the study.
    Series:
      type: object
      properties:
        seriesUid:
          type: string
          description: The UID of the series.
        seriesDescription:
          type: string
          description: The description of the series.
        modality:
          type: string
          description: The modality of the series.
        number:
          type: string
          pattern: "^\\d+$"
          description: The series number.
        instancesUrl:
          type: string
          description: The URL to retrieve the series of the study.
    Instance:
      type: object
      properties:
        number:
          type: string
          pattern: "^\\d+$"
          description: The series number.
        title:
          type: string
          description: The title of the instance.
        sopClassUid:
          type: string
          description: The UID of the SOP class.
        instanceUid:
          type: string
          description: The UID of the instance.
    SuccessResponse:
      type: object
      properties:
        ok:
          type: boolean
          enum: [true]
    ErrorResponse:
      type: object
      properties:
        ok:
          type: boolean
          enum: [false]
        message:
          type: string
    FacetOptions:
      type: array
      items:
        type: object
        properties:
          key:
            type: string
          count:
            type: integer
